language: java

jdk:
- oraclejdk8

deploy:
  provider: heroku
  api_key:
    secure: QVBhs0pwo0EMplpplYGZN5u5NlP4tfC7xH1EEs8qfRRcVJrvn2bRMkGUTLJ7RPKysp5I+hEOW5SMKCcXXAlKWWOfsO54QPKp2i2oWe6T7bMGHeKUDbfa8SRASZrcQTCjTwRThqyF/Ryh3GcYwQyBx8lDE903IZwPR+T3sF86JN3RGKVybM0smcgGvgXDwtzPMs8C8lFUA2921HxcnNkDZB6ns52yFNMkqO9C4Y9vqmMVv4UaPiSg5RDKfO6KNueHRrgN97cvOpbThM2YXqztEadzK9RmUEs8IwMyIQhBRP8gdJG1OS4p5C0uoibg2EwZtuDC4gOZ+nM3EJurHumgyqf9eled05Z9mPkuCK3QlK+FnU9s0pcBLytW3vOcIPJ4ZzJgUzZX4EyP9eiG4svEySiC2Q4g1Sjthplfm/IGVBM5os/kX9HaNulpS0k2sSoBVF2d646a4aJDwTuuW09KzrhZZv6Ux2HeYVKhhjvPI0xR7p6IAJkxM8bF9ABOuQzgx4eHJhu21qySN8PcmQfjEXvrtWBkyP+2+O77z6hjvz4PonfZGzAFGXgN1WFrL7DbU6GVwICBLIwJ9HxFPfw7KJx4Mg1df5Fa+McPAhBG+vFp2mEiqbABom49XBxgMJOfgVXkghK01Qkt3uqwFg5LItELRrs7kTmg4wQqOjmjo5A=
  app: nucourse-api
