logging:
  level: INFO
  loggers:
    com.tylerkindy: DEBUG
  appenders:
    - type: console

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: test
  password: Test123
  url: jdbc:mysql://localhost/courses?useSSL=false
  initialSize: 3
  minSize: 3
  maxSize: 3

server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 8080

webSecurity:
  cors:
    allowedOrigins: "*"

jobs:
  catalogScrapingJob: 3d
